# Generated by Django 2.2.12 on 2020-07-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200719_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lesson',    
            name='title',
            field=models.CharField(max_length=100),
        ),  
    ]
